#!/bin/bash

docker run -it --rm -w "${PWD}" -v "${PWD}:${PWD}"\
                      -v //var/run/docker.sock:/var/run/docker.sock\
                      -v wrapper-slim-sbin:/usr/local/sbin/\
                      dockerbundle/wrapper:slim $*
